openapi: 3.0.2
info:
  title: Courses
  description: "Administration Course Proposals API"
  contact:
    email: anton93lev@gmail.com
  version: 0.0.1-SNAPSHOT
tags:
  - name: Administration Course Proposals API
    description: Administration Course Proposals API
paths:
  /administration/courses-proposals/uuid/approval:
    post:
      tags:
        - Administration Course Proposals API
      summary: Approve Course Proposal
      description: Approve Course Proposal
      operationId: approveCourseProposal
      requestBody:
        description: Course creation request
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/CourseCreateRequest'
        required: true
      responses:
        '200':
          description: New Course created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
        '400':
          description: Validation issues in payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestApiErrorResponse'
        '500':
          description: Unexpected server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestApiErrorResponse'
components:
  schemas:
    CourseCreateRequest:
      description: Course creation model
      type: object
      properties:
        name:
          type: string
          description: Course name
          example: Java 11 for beginners
          required: true
        description:
          type: string
          description: Course description
          example: Course created for Java developers
          required: true
    Course:
      description: Course model
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426655440001
          description: UUID of the company.
          required: true
        name:
          type: string
          description: Course name
          example: Java 11 for beginners
          required: true
        description:
          type: string
          description: Course description
          example: Course created for Java developers
          required: true
    RestApiError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: ErrorCode
          description: Error code.
        details:
          type: array
          description: An array of details about specific errors that led to this reported error.
          items:
            $ref: '#/components/schemas/RestApiError'
        innererror:
          $ref: '#/components/schemas/InnerError'
        message:
          type: string
          example: Validation issues
          description: A human-readable representation of the error.
        target:
          type: string
          example: field
          description: The target of the error.
      title: RestApiError
      description: REST API Error.
    RestApiErrorResponse:
      type: object
      properties:
        error:
          $ref: '#/components/schemas/RestApiError'
      title: RestApiErrorResponse
      description: REST API Error Response. Full description about error response is represented in https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses
    InnerError:
      type: object
      properties:
        code:
          type: string
          example: ErrorCode
          description: Error code.
        innererror:
          $ref: '#/components/schemas/InnerError'
      title: InnerError
      description: An object containing more specific information than the current object about the error.